config/routes.rb
Rails.application.routes.draw do
  root to: "home#index"
  get 'rooms/search'
  resources :rooms
  resources :reservations
  get 'rooms/index'
  get 'home/index'
  get 'users/account'
  post 'reservations/confirm'
  post 'rooms/:id', to: 'reservations#confirm' 
   
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }
  
  devise_scope :user do
    get 'profile_edit', to: 'users/registrations#profile_edit', as: 'profile_edit'
    patch 'profile_update', to: 'users/registrations#profile_update', as: 'profile_update'
  end
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/reservation.rb
class Reservation < ApplicationRecord
  belongs_to:room
  has_many:users, through: :authorizations
  has_many:authorizations
  
   def date
    (self.finish_day - self.start_day).to_int
    end
  
  def date_num
    (self.finish_day - self.start_day).to_int * self.number_of_people
  end
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  before_action :set_reservation, only: %i[ show edit update destroy ]

  # GET /reservations or /reservations.json
  def index
    @rooms = Room.where(user_id: current_user.id)
    @reservations = Reservation.where(user_id: current_user.id)
  end

  # GET /reservations/1 or /reservations/1.json
  def show
    @room = Room.find(params[:id])
    @reservation = Reservation.find(params[:id])
  end

  # GET /reservations/new
  def new
    @reservation = Reservation.new
  end

  def confirm
    @room = Room.find(params[:id])
    @reservation = Reservation.new(reservation_params)
  end
  
  # GET /reservations/1/edit
  def edit
  end

  # POST /reservations or /reservations.json
  def create
    
    @reservation = Reservation.new(reservation_params)

    respond_to do |format|
      if @reservation.save
        format.html { redirect_to @reservation, notice: "Reservation was successfully created." }
        format.json { render :show, status: :created, location: @reservation }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @reservation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reservations/1 or /reservations/1.json
  def update
    respond_to do |format|
      if @reservation.update(reservation_params)
        format.html { redirect_to @reservation, notice: "Reservation was successfully updated." }
        format.json { render :show, status: :ok, location: @reservation }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @reservation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reservations/1 or /reservations/1.json
  def destroy
    @reservation.destroy
    respond_to do |format|
      format.html { redirect_to reservations_url, notice: "Reservation was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_reservation
      @reservation = Reservation.find(params[:id])
    end

    # Only allow a list of trusted parameters through.  ,:user_id, :room_id :total_amount :room_image
    def reservation_params
      params.require(:reservation).permit(:start_day, :finish_day, :number_of_people, :total_amount, :room_id ).merge(user_id: current_user.id)
    end
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/views/reservations/_form.html.erb
<%= form_with(model: reservation) do |form| %>
  <% if reservation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(reservation.errors.count, "error") %> prohibited this reservation from being saved:</h2>

      <ul>
        <% reservation.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :start_day %>
    <%= form.date_select :start_day %>
  </div>

  <div class="field">
    <%= form.label :finish_day %>
    <%= form.date_select :finish_day %>
  </div>

  <div class="field">
    <%= form.label :number_of_people %>
    <%= form.number_field :number_of_people %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/reservations/confirm.html.erb
<div class="container reservation-new">
  <div class="row">
    <div class="col-6 offset-3">
      <div class="reservation-new-nav border p-4">
        <h4 class="pb-3 mb-3 border-bottom">予約内容確認</h4>
        <h5 class="price-icon mt-3">¥<%= @room.room_price %>/日</h5>
        <div class="reservation-new-date-select p-2">
        <form>
          <fieldset disabled>
            <div class="form-group">
              <label>開始日</label>
              <input type="text" id="disabledTextInput" class="form-control" placeholder="<%= @reservation.start_day %>">
            </div>
            <div class="form-group">
              <label>終了日</label>
              <input type="text" id="disabledTextInput" class="form-control" placeholder="<%= @reservation.finish_day %>">
            </div>
          <h6 class="pb-4 mb-4 border-bottom">使用日数：<%= @reservation.date %>日</h6>
          <h6 class="pb-4 mb-4 border-bottom">人数：<%= @reservation.number_of_people %>人</h6>
          <div class="form-group">
              <label>合計金額</label>
              <input type="text" id="disabledTextInput" class="form-control" placeholder="<%= @room.room_price * @reservation.date_num %>">
            </div>
          <p class="reservation-new-check-content pb-4 mb-4 border-bottom">上記内容でよろしければ「予約を確定」を押してください</p>
          </fieldset>
        </form>
        
          <%= form_for @reservation do |f| %>
          　<%= f.hidden_field :room_id, value: @room.id %>
            <%= f.hidden_field :start_day, class: "d-none" %>
            <%= f.hidden_field :finish_day %>
            <%= f.hidden_field :number_of_people %>
            <%= f.hidden_field :total_amount, value: @room.room_price * @reservation.date_num %>
            
            <%= f.submit"予約を確定",class: "btn btn-primary  btn-block" %>
            <%= link_to 'ルーム詳細に戻る', room_path, class: "btn btn-outline-primary text-blue  btn-block" %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/reservations/edit.html.erb
<h1>Editing Reservation</h1>

<%= render 'form', reservation: @reservation %>

<%= link_to 'Show', @reservation %> |
<%= link_to 'Back', reservations_path %>

app/views/reservations/index.html.erb
<div class="container">
<h2>予約済ルーム一覧</h2>
<table class="table table-striped table-bordered">
  <thead>
    <tr>
      <th>ルーム画像</th>
      <th>ルーム名</th>
      <th>ルーム紹介</th>
      <th>合計料金</th>
      <th>開始日</th>
      <th>終了日</th>
      <th>予約確定日時</th>
    </tr>
  </thead>

  <tbody>
    <% @reservations.each do |reservation| %>
    <% @rooms.each do |room| %>
      <tr>
        <td><%= image_tag room.room_image.to_s,class: "room-image" %></td>
        <td class="room-name"><%= link_to"#{room.room_name}", room %></td>
        <td><%= room.room_introduction %></td>
        <td>¥<%= reservation.total_amount %></td>
        <td><%= reservation.start_day %></td>
        <td><%= reservation.finish_day %></td>
        <td><%= reservation.created_at.to_s(:datetime_jp) %></td>
      </tr>
    <% end %>
    <% end %>
  </tbody>
</table>
</div>

app/views/reservations/show.html.erb
<div class="container-fiuld user">
  <div class="row">
    <div class="user-view col-12 bg-light h-100">
      <div class="user-view-box">
        <div class="update-content">
          <div class="row">
            <p class="col-3">予約した部屋</p>
            <div class="col-9">
              <%= @room.room_name %>
            </div>
          </div>
        </div>
        <div class="update-content">
          <div class="row">
            <p class="col-3">開始日</p>
            <div class="col-9">
              <%= @reservation.start_day %>
            </div>
          </div>
        </div>
        <div class="update-content">
          <div class="row">
            <p class="col-3">終了日</p>
            <div class="col-9">
              <%= @reservation.finish_day %>
            </div>
          </div>
        </div>
        <div class="update-content">
          <div class="row">
            <p class="col-3">価格</p>
            <div class="col-9">
              <%= @reservation.total_amount %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>